# ============================================================
# Profile: production
# ============================================================
spring.application.name=PatientsAppointmentsBookingApp [PROD]

logging.level.root=WARN
logging.level.com.example.pams=INFO

# Suppress ANSI colour codes in production logs
spring.output.ansi.enabled=NEVER
