# ============================================================
# Profile: development
# ============================================================
spring.application.name=PatientsAppointmentsBookingApp [DEV]

logging.level.root=DEBUG
logging.level.com.example.pams=DEBUG

# Human-readable console output
spring.output.ansi.enabled=ALWAYS
